name: calendar
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  #sdk: '>=3.0.0-3.0.dev <4.0.0'
  sdk: '>=2.19.0-444.4.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  floor_generator:
  raised_buttons: 
  search_page: 
  intl:
  animated_splash_screen:
  lottie:

  flutter_local_notifications: ^9.9.1
  google_fonts:
  get_storage:
  page_animation_transition:
  cupertino_icons: ^1.0.2
  get:
  floor:
  
  
  

dev_dependencies: 
  flutter_test:
    sdk: flutter
  build_runner:


  
  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
